name: pill-counter

channels:
  - conda-forge

dependencies:
  - flake8 >= 4.0.1
  - isort >= 5.10.1
  - keras >= 2.6.0
  - matplotlib >= 3.5.1
  - numpy >= 1.19.5
  - pandas >= 1.3.5
  - py-xgboost >= 1.5.0
  - python >= 3.9.7
  - pytorch >= 1.9.0
  - ruamel.yaml >= 0.17.19
  - scikit-image >= 0.19.1
  - streamlit >= 1.3.1
  - tensorflow >= 2.6.2
